AllCops:
  TargetRubyVersion: 2.7.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - Gemfile

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/GuardClause:
  MinBodyLength: 5

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma

Style/MixinUsage:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false
  AllowBeforeTrailingComments: false
  ForceEqualSignAlignment: false

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent
  IndentationWidth: ~

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
  IndentationWidth: ~

Layout/AssignmentIndentation:
  Enabled: true
  IndentationWidth: ~

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
  IndentationWidth: ~

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline

Layout/TrailingWhitespace:
  Enabled: true
  AllowInHeredoc: false

Layout/LineLength:
  Max: 120

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
